openapi: 3.0.3
info:
  title: API de Patrocinios
  version: 1.0.0
  description: API para gestionar patrocinios de pilotos.

paths:
  /patrocinios/partes_piloto/{id_piloto}:
    get:
      summary: Obtener las partes disponibles de un piloto para patrocinio
      tags:
        - Patrocinios
      parameters:
        - name: id_piloto
          in: path
          required: true
          schema:
            type: integer
          description: ID del piloto.
      responses:
        "200":
          description: Lista de partes disponibles para patrocinio del piloto.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      partes:
                        type: array
                        items:
                          type: object
                          properties:
                            id_parte:
                              type: integer
                              example: 5
                            nombre_parte:
                              type: string
                              example: "Hombro Derecho"
                            descripcion_parte:
                              type: string
                              example: "Espacio en el hombro derecho del traje del piloto"
                            precio_parte:
                              type: string
                              example: "500.00"
                            parte_disponible:
                              type: object
                              properties:
                                type:
                                  type: string
                                  example: "Buffer"
                                data:
                                  type: array
                                  items:
                                    type: integer
                                    example: 1
                      piloto:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          altura:
                            type: string
                            example: "170"
                          arl:
                            type: string
                            example: "sura"
                          tipo_sangre_id:
                            type: integer
                            example: 1
                          extra_por_patrocinio:
                            type: string
                            example: "10"
        "400":
          description: Error de validación de ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "El ID debe ser un número."
        "404":
          description: Piloto no encontrado o sin partes disponibles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "El piloto no tiene partes disponibles."
        "500":
          description: Error en la consulta a la base de datos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error al consultar la base de datos."

  /patrocinios/create_patrocinio_piloto:
    post:
      summary: Crear patrocinio para un piloto
      tags:
        - Patrocinios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id_entidad:
                    type: integer
                    example: 1
                  partes_patrocinio:
                    type: array
                    items:
                      type: object
                      properties:
                        id_parte:
                          type: integer
                          example: 5
                        nombre:
                          type: string
                          example: "Hombro Derecho"
                        precio:
                          type: number
                          example: 500.00
                  subtotal:
                    type: number
                    example: 500.00
                  porcentaje_aumento_entidad:
                    type: string
                    example: "10"
                  total:
                    type: number
                    example: 550.00
      responses:
        "200":
          description: Patrocinio creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Patrocinio creado exitosamente."
        "400":
          description: Error de validación de datos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "El campo id_entidad es requerido."
        "404":
          description: Parte no disponible.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Hombro Derecho no está disponible."
        "500":
          description: Error en la consulta a la base de datos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error al crear patrocinio."
